apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trema
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: trema=ghcr.io/clubcedille/trema:latest
    argocd-image-updater.argoproj.io/trema.update-strategy: digest
spec:
  project: default
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production
    namespace: trema
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production
    path: apps/trema/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
