apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - httpproxy.yaml
  - ../base
# ../base/kubero.yaml has a reference to the namespace, to change for other clubs
