apiVersion: apps/v1
kind: Deployment
metadata:
  name: commandes
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      containers:
        - name: commandes
          image: us.gcr.io/fine-harbor-276700/patchets/commandes:latest
          ports:
          - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
          envFrom:
            # Configuration comes from the configmap and the secrets.
            - configMapRef:
                name: commandes-config
            - secretRef:
                name: app-secrets
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      imagePullSecrets:
        - name: gcrcedille-pull
