apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: patchets

resources:
  - deployment.yaml
  - service.yaml
  - autoscaler.yaml
  # - seeder.yaml # TODO: Uncomment when seeding is needed.

configMapGenerator:
  - name: commandes-config
    literals:
      - RAILS_ENV=production
      - SQUARE_ENV=production
      - DATABASE_PORT=5432

images:
  - name: us.gcr.io/fine-harbor-276700/patchets/commandes
    newTag: 1.5.0

helmCharts:
  - name: postgresql
    releaseName: commandes-db
    # version: 16.4.16
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      auth:
        username: commandes_patchets_user
        database: commandes_patchets2
        existingSecret: commandes-patchets-secret
        primary:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: cephfs
