apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: patchets

resources:
- deployment.yaml
- service.yaml
- autoscaler.yaml
- ingress.yaml
- secrets.yaml
# - seeder.yaml # TODO: Uncomment when seeding is needed.

configMapGenerator:
- name: commandes-config
  envs: 
  - config/.base_env

commonLabels:
  app.kubernetes.io/name: commandes
  app.kubernetes.io/instance: commandes

  
configMapGenerator:
- name: commandes-config
  behavior: replace
  literals:
    - RAILS_ENV=production
    - SQUARE_ENV=production

images:
- name: us.gcr.io/fine-harbor-276700/patchets/commandes
  newTag: 1.5.0

helmCharts:
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 12.11.4
  releaseName: commandes-db
  namespace: patchets
  valuesInline:
    auth:
      username: commandes
      password: commandes-password
      database: commandes_db
    primary:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: cephfs
