apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: patchets

resources:
- deployment.yaml
- service.yaml
- autoscaler.yaml
- secrets.yaml
# - seeder.yaml # TODO: Uncomment when seeding is needed.

configMapGenerator:
- name: commandes-config
  envs: 
  - config/.base_env

commonLabels:
  app.kubernetes.io/name: commandes
  app.kubernetes.io/instance: commandes

  
configMapGenerator:
- name: commandes-config
  literals:
    - RAILS_ENV=production
    - SQUARE_ENV=production
    - DATABASE_HOST=commandes-db-postgresql
    - DATABASE_PORT=5432
    - DATABASE_NAME=commandes_db
    - DATABASE_USER=commandes

images:
- name: us.gcr.io/fine-harbor-276700/patchets/commandes
  newTag: 1.5.0

helmCharts:
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 16.4.16
  releaseName: commandes-db
  namespace: patchets
  valuesInline:
    primary:
      extraEnvVars:
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
    primary:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: cephfs
