apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pont-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - pontacier.prod.cedille.club
      secretName: pont-website-tls
  rules:
    - host: pontacier.prod.cedille.club
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pont-wordpress
                port:
                  name: http
