apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: markets-backend
spec:
  serviceName: "markets-backend-service"
  replicas: 1
  selector:
    matchLabels:
      app: markets-backend
  template:
    metadata:
      labels:
        app: markets-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/algoets/markets-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: markets-env-secret
          volumeMounts:
            - name: db-storage
              mountPath: /app/markets/db
      imagePullSecrets:
        - name: ghcr-secret
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cephfs
        resources:
          requests:
            storage: "10Gi"
