apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  instances: 1
  bootstrap:
    initdb:
      database: markets
      owner: markets
      secret:
        name: cnpg-secret
  storage:
    size: 5Gi
    storageClass: cephfs
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: markets-pooler-rw
  namespace: markets
spec:
  cluster:
    name: cnpg
  type: rw
  instances: 3
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "20"
      min_pool_size: "5"
      ignore_startup_parameters: "extra_float_digits,options"
