apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calidum-rotae
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production
    namespace: calidum-rotae
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production
    path: apps/calidum-rotae/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
