apiVersion: v1
kind: Service
metadata:
  name: pont-wordpress
  namespace: pontacier
  labels:
    app: pont
spec:
  ports:
    - name: http
      targetPort: 80
      protocol: TCP
      port: 80
  type: ClusterIP
  selector:
    app: pont
    tier: frontend
