apiVersion: apps/v1
kind: Deployment
metadata:
  name: pont-wordpress
  namespace: pontacier
  labels:
    app: pont
spec:
  selector:
    matchLabels:
      app: pont
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pont
        tier: frontend
    spec:
      containers:
      - image: us.gcr.io/fine-harbor-276700/wordpress-pont-acier:v1.0.0
        name: pont-wordpress
        envFrom:
        - secretRef:
            name: pont-secret
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pont-wordpress-persistent-storage
          mountPath: /var/www/html
        resources: {}
      volumes:
      - name: pont-wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: pont-wp-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pont-wp-pv-claim
  namespace: pontacier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs
