apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: wiki
    releaseName: wiki
    version: 2.2.17
    repo: https://charts.js.wiki
    valuesInline:
      image.tag: 2.5
      image.pullPolicy: Always
      resources.limits:
        cpu: 200m
        memory: 256Mi
      ingress.enabled: false
      postgresql:
        existingSecret: wikijs-postgres-secret
        persistence:
          enabled: true
          size: 10Gi
          storageClass: cephfs
      startupProbe:
        initialDelaySeconds: 120
