apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grav
  name: grav
  annotations:
    kube-score/ignore: container-image-tag,container-security-context-readonlyrootfilesystem, container-security-context-user-group-id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav
  template:
    metadata:
      labels:
        app: grav
    spec:
      containers:
      - name: grav
        image: ghcr.io/clubcedille/grav:latest
        imagePullPolicy: Always
        env:
        - name: HEAD_BRANCH
          value: master
        envFrom:
        - secretRef:
            name: grav-config
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: grav-accounts
          mountPath: /var/www/html/user/accounts
        - name: grav-data
          mountPath: /var/www/html/user/data
      # group 33 is www-data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
            ephemeral-storage: 512Mi
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes:
      - name: grav-accounts
        persistentVolumeClaim:
          claimName: grav-accounts-pvc
      - name: grav-data
        persistentVolumeClaim:
          claimName: grav-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-accounts-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-data-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
