apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-cedille
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-cedille
  template:
    metadata:
      labels:
        app: wiki-cedille
    spec:
      containers:
        - name: wiki-cedille
          image: ghcr.io/clubcedille/wiki-cedille:latest
          imagePullPolicy: Always
          env:
            - name: NGINX_ENABLE_ABSOLUTE_REDIRECT
              value: "yes"
            - name: NGINX_ENABLE_PORT_IN_REDIRECT
              value: "yes"
            - name: NGINX_HTTP_PORT_NUMBER
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-cedille-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-cedille-stg
  template:
    metadata:
      labels:
        app: wiki-cedille-stg
    spec:
      containers:
        - name: wiki-cedille-stg
          image: ghcr.io/clubcedille/wiki-cedille:staging
          imagePullPolicy: Always
          env:
            - name: NGINX_ENABLE_ABSOLUTE_REDIRECT
              value: "yes"
            - name: NGINX_ENABLE_PORT_IN_REDIRECT
              value: "yes"
            - name: NGINX_HTTP_PORT_NUMBER
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
