apiVersion: v1
kind: Service
metadata:
  name: trema
spec:
  selector:
    app: trema
  ports:
    - name: http
      targetPort: 6000
      protocol: TCP
      port: 80
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
