apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: patchets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16.4
          env:
            - name: POSTGRES_USER
              value: commandes_patchets_user
            - name: POSTGRES_DB
              value: commandes_patchets2
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commandes-patchets-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: data-commandes-db-postgresql-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: patchets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: cephfs
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: patchets
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
