apiVersion: v1
kind: Service
metadata:
  name: calidum-rotae-service
  namespace: calidum-rotae
spec:
  selector:
    app: calidum-rotae
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
