name: test kube-score2

on:
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  test-ks:
    uses:
      clubcedille/cedille-workflows/.github/workflows/kube-score-validator.yml@test-new-kscore